# Site settings
title: Rui Zhao
name: Rui Zhao
description: My blog
url: https://rz0718.github.io
baseurl: ""
repository: rz0718/rz0718.github.io

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Site Author
author:
  name: "Rui Zhao"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Researcher, Quant, Educator and Dad"
  location: "Singapore"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:rui91seu@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rz0718"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rui-zhao-ph-d-cfa-1b4288112/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=u4hCFPIAAAAJ&hl=en"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Reading Files
include:
  - _pages
  - assets
  - assets/images
  - assets/images/books

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _templates
  - README.md 