# Site settings
title: Blog by RZ
name: 
description: My blog
url: https://rz0718.github.io
baseurl: ""
repository: rz0718/rz0718.github.io

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Site Author
author:
  name: "Rui Zhao(赵锐)"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "茫茫宇宙，好像荒野"
  location: "Singapore"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:rui91seu@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rz0718"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rui-zhao-ph-d-cfa-1b4288112/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=u4hCFPIAAAAJ&hl=en"

# Defaults
defaults:
  # _posts/articles
  - scope:
      path: "_posts/articles"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_label: "Table of Contents"
  
  # _posts/notes
  - scope:
      path: "_posts/notes"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: false
      toc_sticky: false
  
  # _posts/blogs
  - scope:
      path: "_posts/blogs"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: false
      toc_sticky: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Reading Files
include:
  - _pages
  - assets
  - assets/images
  - assets/images/books

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _templates
  - README.md 