title: Rui Zhang
name: Rui Zhang
description: Software Engineer @ Pluang
url: https://rz0718.github.io
repository: rz0718/rz0718.github.io

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

# Site settings
locale: "en-US"
search: false

# Site Author
author:
  name: "Rui Zhang"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer @ Pluang"
  location: "Singapore"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ruizhang0718@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rz0718"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rui-zhang-0718"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rz0718"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rui-zhang-0718"

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor 